### ISSUE TITLE
multisig settings page

### ISSUE THREAD

**Issue by whyrusleeping** [slate-engineering/wallet#9]
Users need to be able to modify their multisig parameters.
![IMG_5F90E536B4FC-1](https://user-images.githubusercontent.com/1243164/107296404-26f7af00-6a26-11eb-9417-6b9feb35e928.jpeg)

The key things we can do here:
- Changing signing threshold (the '2' value in the image)
- Add an additional signer
- Remove a signer
- Swap one signer for another

**Comment by jimmylee** [comment]
We didn't get swap. But we'll get it next time.
